const dataPeserta = [
  // PROMAGH - HIJAU
  {
    id: "PGH001",
    nama: "Rahma Fitriyanti",
    kelas: "10-2",
    kelompok: "Promagh",
  },
  {
    id: "PGH002",
    nama: "Asyifa Nur Fadilah Ramadani",
    kelas: "10-7",
    kelompok: "Promagh",
  },
  {
    id: "PGH003",
    nama: "Haura Twina Rahmawati",
    kelas: "10-2",
    kelompok: "Promagh",
  },
  {
    id: "PGH004",
    nama: "Sintia Dewi Anggraeni",
    kelas: "10-4",
    kelompok: "Promagh",
  },
  {
    id: "PGH005",
    nama: "sheila Adelia",
    kelas: "10-11",
    kelompok: "Promagh",
  },
  {
    id: "PGH006",
    nama: "Yasfi Jilan Zahidah",
    kelas: "10-7",
    kelompok: "Promagh",
  },
  {
    id: "PGH007",
    nama: "Geanita Putri Azahra",
    kelas: "10-4",
    kelompok: "Promagh",
  },
  {
    id: "PGH008",
    nama: "Zulfa Adinda Luthfiah",
    kelas: "10-3",
    kelompok: "Promagh",
  },
  {
    id: "PGH009",
    nama: "Aisyah Nurfitri",
    kelas: "10-11",
    kelompok: "Promagh",
  },
  {
    id: "PGH010",
    nama: "Kania Regina Putri",
    kelas: "10-7",
    kelompok: "Promagh",
  },

  // MIXSAGRIP - KUNING
  {
    id: "MSG001",
    nama: "NINDYA SHAFIRA",
    kelas: "10-7",
    kelompok: "Mixsagrip",
  },
  {
    id: "MSG002",
    nama: "CINTYA AZAHRA",
    kelas: "10-2",
    kelompok: "Mixsagrip",
  },
  {
    id: "MSG003",
    nama: "Checilia Al Maira Putri",
    kelas: "10-11",
    kelompok: "Mixsagrip",
  },
  {
    id: "MSG004",
    nama: "Salwa Nisrina Zahran",
    kelas: "11-1",
    kelompok: "Mixsagrip",
  },
  {
    id: "MSG005",
    nama: "Naila Qurrotul Uyun",
    kelas: "10-12",
    kelompok: "Mixsagrip",
  },
  {
    id: "MSG006",
    nama: "Resti virjinia rajabani",
    kelas: "10-1",
    kelompok: "Mixsagrip",
  },
  {
    id: "MSG007",
    nama: "TRI Melati",
    kelas: "10-4",
    kelompok: "Mixsagrip",
  },
  {
    id: "MSG008",
    nama: "Samira Putri Kanaya",
    kelas: "10-8",
    kelompok: "Mixsagrip",
  },
  {
    id: "MSG009",
    nama: "REIHANA NAZWA AULIYA",
    kelas: "10-8",
    kelompok: "Mixsagrip",
  },
  {
    id: "MSG010",
    nama: "Ai Hafidah Nurhasanah",
    kelas: "10-2",
    kelompok: "Mixsagrip",
  },

  // BODREK - MERAH
  {
    id: "BDK001",
    nama: "Thasya seni ade rahayu",
    kelas: "10-12",
    kelompok: "Bodrek",
  },
  {
    id: "BDK002",
    nama: "Anisa Puspitasari",
    kelas: "10-6",
    kelompok: "Bodrek",
  },
  {
    id: "BDK003",
    nama: "DHIFANI AZKIA LATIFA",
    kelas: "10-3",
    kelompok: "Bodrek",
  },
  {
    id: "BDK004",
    nama: "Zidna Syakira",
    kelas: "10-3",
    kelompok: "Bodrek",
  },
  {
    id: "BDK005",
    nama: "Lorissa Amelia",
    kelas: "10-4",
    kelompok: "Bodrek",
  },
  {
    id: "BDK006",
    nama: "Amalia Putri Azzahra",
    kelas: "10-3",
    kelompok: "Bodrek",
  },
  {
    id: "BDK007",
    nama: "Keyza Nasytha",
    kelas: "10-5",
    kelompok: "Bodrek",
  },
  {
    id: "BDK008",
    nama: "Albaransyah Banyu Astira",
    kelas: "11-2",
    kelompok: "Bodrek",
  },
  {
    id: "BDK009",
    nama: "HERNAWATI JULIANA",
    kelas: "10-6",
    kelompok: "Bodrek",
  },
  {
    id: "BDK010",
    nama: "syavira nurul azzahra",
    kelas: "10-5",
    kelompok: "Bodrek",
  },

  // PARACETAMOL - BIRU
  {
    id: "PCM001",
    nama: "Anisa Febriani",
    kelas: "10-2",
    kelompok: "Paracetamol",
  },
  {
    id: "PCM002",
    nama: "Tsabilla Erliana Injayani",
    kelas: "10-3",
    kelompok: "Paracetamol",
  },
  {
    id: "PCM003",
    nama: "Ai SURYANI",
    kelas: "10-5",
    kelompok: "Paracetamol",
  },
  {
    id: "PCM004",
    nama: "Daffa' Fauzan Anshori",
    kelas: "10-12",
    kelompok: "Paracetamol",
  },
  {
    id: "PCM005",
    nama: "Salwa Alifia",
    kelas: "10-7",
    kelompok: "Paracetamol",
  },
  {
    id: "PCM006",
    nama: "Fitria Alfa Risa Napitupulu",
    kelas: "10-8",
    kelompok: "Paracetamol",
  },
  {
    id: "PCM007",
    nama: "silvia nurul khasanah",
    kelas: "10-1",
    kelompok: "Paracetamol",
  },
  {
    id: "PCM008",
    nama: "Hafsha Habudzul A'shfi",
    kelas: "10-12",
    kelompok: "Paracetamol",
  },
  {
    id: "PCM009",
    nama: "Muhamad Rizki Al Furkon",
    kelas: "11-10",
    kelompok: "Paracetamol",
  },
  {
    id: "PCM010",
    nama: "LESTARI",
    kelas: "10-11",
    kelompok: "Paracetamol",
  },

  // MAXSILIN - UNGU
  {
    id: "MSL001",
    nama: "Hilda Nuraeni Asropiah",
    kelas: "10-8",
    kelompok: "Maxsilin",
  },
  {
    id: "MSL002",
    nama: "SYIFA HANIFAH",
    kelas: "10-7",
    kelompok: "Maxsilin",
  },
  {
    id: "MSL003",
    nama: "Zaskia Anggun Utami",
    kelas: "10-4",
    kelompok: "Maxsilin",
  },
  {
    id: "MSL004",
    nama: "Recha Alilah nurhibatullah",
    kelas: "10-8",
    kelompok: "Maxsilin",
  },
  {
    id: "MSL005",
    nama: "SIPA NURAENI",
    kelas: "10-9",
    kelompok: "Maxsilin",
  },
  {
    id: "MSL006",
    nama: "Puspita nurmeilasari",
    kelas: "10-5",
    kelompok: "Maxsilin",
  },
  {
    id: "MSL007",
    nama: "BILQIS ZALFA TAKBIRANI",
    kelas: "10-5",
    kelompok: "Maxsilin",
  },
  {
    id: "MSL008",
    nama: "NAYLA KHAIRUNNISA",
    kelas: "10-6",
    kelompok: "Maxsilin",
  },
  {
    id: "MSL009",
    nama: "NIDA FARIDAH NURHASANAH",
    kelas: "10-4",
    kelompok: "Maxsilin",
  },
  {
    id: "MSL010",
    nama: "DZAKHIRA AYYATURRAHMAN",
    kelas: "10-9",
    kelompok: "Maxsilin",
  },

  // PANADOL - PUTIH
  {
    id: "PND001",
    nama: "REGINA MEXICO APRILYANTY",
    kelas: "10-2",
    kelompok: "Panadol",
  },
  {
    id: "PND002",
    nama: "Delphinia",
    kelas: "10-8",
    kelompok: "Panadol",
  },
  {
    id: "PND003",
    nama: "Evi Anggraeni",
    kelas: "10-6",
    kelompok: "Panadol",
  },
  {
    id: "PND004",
    nama: "NIDA ALISIA FAJRIN",
    kelas: "10-1",
    kelompok: "Panadol",
  },
  {
    id: "PND005",
    nama: "Siti komala sari",
    kelas: "10-7",
    kelompok: "Panadol",
  },
  {
    id: "PND006",
    nama: "Luthfiah Nur Azizah",
    kelas: "10-3",
    kelompok: "Panadol",
  },
  {
    id: "PND007",
    nama: "Naila Tsamrotul Ainiyah",
    kelas: "10-12",
    kelompok: "Panadol",
  },
  {
    id: "PND008",
    nama: "DELLA ZULFA FAOZIA",
    kelas: "10-7",
    kelompok: "Panadol",
  },
  {
    id: "PND009",
    nama: "LISNAWATI",
    kelas: "11-2",
    kelompok: "Panadol",
  },
  {
    id: "PND010",
    nama: "Sri Nuraeni",
    kelas: "10-12",
    kelompok: "Panadol",
  },

  // TOLAK ANGIN - OREN
  {
    id: "TLA001",
    nama: "JIAN DWI LESTARI",
    kelas: "10-3",
    kelompok: "Tolak Angin",
  },
  {
    id: "TLA002",
    nama: "Saskia Yoshita",
    kelas: "10-2",
    kelompok: "Tolak Angin",
  },
  {
    id: "TLA003",
    nama: "RISMA RINI FAUZI SURYANI",
    kelas: "10-3",
    kelompok: "Tolak Angin",
  },
  {
    id: "TLA004",
    nama: "Inas nur syahidah",
    kelas: "10-2",
    kelompok: "Tolak Angin",
  },
  {
    id: "TLA005",
    nama: "Raisya Azkayra Shafira",
    kelas: "10-6",
    kelompok: "Tolak Angin",
  },
  {
    id: "TLA006",
    nama: "Ghisellha Reysha Putri Nugraha",
    kelas: "10-8",
    kelompok: "Tolak Angin",
  },
  {
    id: "TLA007",
    nama: "Alena sangki",
    kelas: "10-9",
    kelompok: "Tolak Angin",
  },
  {
    id: "TLA008",
    nama: "Alya nur syifa",
    kelas: "10-10",
    kelompok: "Tolak Angin",
  },
  {
    id: "TLA009",
    nama: "Anggi camelia putri",
    kelas: "10-2",
    kelompok: "Tolak Angin",
  },
];
